# Generated by Django 3.2.5 on 2021-07-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_currencies_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencies',
            name='percentage',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
