# Generated by Django 3.2.5 on 2021-07-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_currencies_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='price',
            field=models.IntegerField(max_length=30, null=True),
        ),
    ]
