# Generated by Django 3.2.5 on 2021-07-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_currencies_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
